---
- name: Include variables
  ansible.builtin.import_role:
    name: lihas_variables
  when: configspaces is not defined

- name: Lihas_become init
  ansible.builtin.set_fact:
    lihas_become: "{{ lihas_become | default(false) }}"
- name: Check if become is necessary
  ansible.builtin.set_fact:
    lihas_become: true
  when: ansible_effective_user_id != 0
- name: Check if become is necessary
  ansible.builtin.set_fact:
    lihas_become: "yes"
  when: ansible_effective_user_id != "root"

## install fail2ban
#
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  notify: Restart fail2ban
  become: "{{ lihas_become }}"

## set journald default source
#
- name: Create local-backend.conf
  community.general.ini_file:
    dest: /etc/fail2ban/jail.d/local-backend.conf
    mode: "0400"
    section: DEFAULT
    option: backend
    value: systemd
    backup: false
  notify: Restart fail2ban
  become: "{{ lihas_become }}"

- name: Create local-banaction
  community.general.ini_file:
    dest: /etc/fail2ban/jail.d/local-banaction.conf
    mode: "0400"
    section: DEFAULT
    option: banaction
    value: "%(banaction_allports)s"
    backup: false
  notify: Restart fail2ban
  become: "{{ lihas_become }}"


## set journald Logtarget
#
- name: Create fail2ban.local
  community.general.ini_file:
    dest: /etc/fail2ban/jail.d/logtarget.local
    mode: "0400"
    section: DEFAULT
    option: logtarget
    value: STDERR
    backup: false
  notify: Restart fail2ban
  become: "{{ lihas_become }}"


## Defaults
#
- name: Create local-times.conf
  community.general.ini_file:
    dest: /etc/fail2ban/jail.d/findtime.conf
    mode: "0400"
    section: DEFAULT
    option: findtime
    value: 1d
    backup: false
  notify: Restart fail2ban
  become: "{{ lihas_become }}"


 ##
- name: Find ignore IPs
  ansible.builtin.set_fact:
    lihas_fail2ban_ignoreip: >-
      {{ lihas_fail2ban_ignoreip | default([]) +
      hostvars[inventory_hostname][item]['config']['fail2ban']['ignoreip'] | default([]) }}
  loop: "{{ configspaces }}"

- name: Display fail2ban ignore IPs
  ansible.builtin.debug:
    var: lihas_fail2ban_ignoreip
    verbosity: 2

- name: Add IPs to local-times.conf
  community.general.ini_file:
    dest: /etc/fail2ban/jail.d/ignoreip.conf
    mode: "0400"
    section: DEFAULT
    option: ignoreip
    value: "{{ lihas_fail2ban_ignoreip | default([]) | join(' ') }}"
    backup: false
  notify: Restart fail2ban
  become: "{{ lihas_become }}"


## ssh
#
- name: Ssh LogLevel VERBOSE
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/fail2ban.conf
    line: LogLevel VERBOSE
    create: true
    mode: "0400"
  notify: Restart ssh
  become: "{{ lihas_become }}"


## Apache config if /etc/apache2 exists
# this will add configuration for apache2
# running it agian  WILL NOT remove the configuration when apache2 no longer exists on the server
- name: Check if /etc/apache2 exists
  ansible.builtin.stat:
    path: /var/log/apache2
  register: apache2

- name: 'Include play: apache2_configure.yml'
  ansible.builtin.include_tasks:
    file: apache2_configure.yml
  when: lihas_fail2ban_apache | default(true) and apache2.stat.exists

...
